cc_test(
    name = "add",
    srcs = ["add.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "mul",
    srcs = ["mul.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "relu",
    srcs = ["relu.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "relu6",
    srcs = ["relu6.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "leakyrelu",
    srcs = ["leakyrelu.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "l2normalize",
    srcs = ["l2normalize.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "conv2d_fc_quant8",
    srcs = ["conv2d_fc_quant8.c"],
    deps = ["//:ovxlib", "@VIV_SDK//:VIV_SDK_LIB"],
    visibility = ["//visibility:public"],
)
